# Introduction

In [1]:
print("hello world")

hello world

In [2]:
print(2+2)
print(4+4)

4
8

In [3]:
print("hello " + "world")

hello world

In [4]:
print("hello world", 2+2, "this is python")
print("hello world", 2+2, "this is python", sep="")

hello world 4 this is python
hello world4this is python

In [5]:
print("hello" + 5)

TypeError: can only concatenate str (not "int") to str

# Variables

In [6]:
# mobile store
price = 900
print("Price of mobile is: $", price, sep="")

Price of mobile is: $900

In [7]:
brand = "Apple"
print("Brand of the mobile is:", brand)

Brand of the mobile is: Apple

In [8]:
ram = 4
print("RAM of the mobile is: ", ram, "GB", sep="")

RAM of the mobile is: 4GB

In [9]:
storage = 128
print("Storage of the mobile is: ", storage, "GB", sep="")

Storage of the mobile is: 128GB

In [10]:
is_billed = True
print(is_billed)

True

In [11]:
type(price)

int

In [12]:
type(brand)

str

In [13]:
type(is_billed)

bool

In [14]:
bill = price + price
print(bill//2) # integer division
print(bill/2) # float division

900
900.0

In [15]:
discount = 15
price_after_discount = price - discount
print(price_after_discount)

885

In [16]:
# implicit conversion
discount = price * 0.045
price_after_discount = price - discount
print(price_after_discount)

859.5

In [17]:
# explicit conversion
type(str(price))

str

# List

In [18]:
brand_list = ["Apple", "LG", "Samsung", "Apple"]
price_list = [900, 850, 875, 1000]
ram_list = [4, 8, 8, 16]
storage_list = [64, 128, 128, 256]

In [19]:
type(brand_list)

list

In [20]:
len(brand_list)

4

In [21]:
min(price_list)

850

In [22]:
max(price_list)

1000

In [23]:
price_list[2]

875

In [24]:
price_list[0:3] # o is inclusive and 3 is exclusive

[900, 850, 875]

In [25]:
price_list[-1]

1000

In [26]:
brand_list[3] = "Motorola"
brand_list

['Apple', 'LG', 'Samsung', 'Motorola']

In [27]:
storage_list.pop()
storage_list

[64, 128, 128]

In [28]:
storage_list.append(512)
storage_list

[64, 128, 128, 512]

# Tuple

In [29]:
storage = (32, 64, 128, 256)
storage

(32, 64, 128, 256)

In [30]:
type(storage)

tuple

In [31]:
storage[0] = 128 # throws error

TypeError: 'tuple' object does not support item assignment

# Dictionary

In [32]:
attributes = {
    "brand": brand_list,
    "storage": storage_list,
    "price": price_list,
    "ram": ram_list
}
attributes

{'brand': ['Apple', 'LG', 'Samsung', 'Motorola'],
 'storage': [64, 128, 128, 512],
 'price': [900, 850, 875, 1000],
 'ram': [4, 8, 8, 16]}

In [33]:
attributes["brand"][1]

'LG'

In [34]:
attributes.keys()

dict_keys(['brand', 'storage', 'price', 'ram'])

In [35]:
attributes.values()

dict_values([['Apple', 'LG', 'Samsung', 'Motorola'], [64, 128, 128, 512], [900, 850, 875, 1000], [4, 8, 8, 16]])

# Conditional Statement

In [36]:
budget = int(input("Enter your budget:"))
if price <= budget:
    print("Congrats")
else:
    print("Your budget is lesser than price")

Enter your budget:900
Congrats

In [37]:
mem = int(input("enter memory"))
if(mem == 32):
    print("Phone price is $600")
elif(mem == 64):
    print("Phone price is $750")
elif(mem == 128):
    print("Phone price is $900")
else:
    print("Please enter a valid memory size")

enter memory128
Phone price is $900

# Loop

In [38]:
range(6)

range(0, 6)

In [39]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [40]:
list(range(1, 6)) # 1 is inclusive, 6 is exclusive

[1, 2, 3, 4, 5]

In [41]:
list(range(6, 20, 2)) # 6 is inclusive, 20 is exclusive

[6, 8, 10, 12, 14, 16, 18]

In [42]:
price = 900
for i in range(5, 21, 5):
    discount = price * i/100
    discounted_price = price - discount
    print("The price after discount", i, "percent is $", discounted_price)

The price after discount 5 percent is $ 855.0
The price after discount 10 percent is $ 810.0
The price after discount 15 percent is $ 765.0
The price after discount 20 percent is $ 720.0

In [43]:
price = 900
i = 5
while i <= 20:
    discount = price * i/100
    discounted_price = price - discount
    print("The price after discount", i, "percent is $", discounted_price)
    i += 5

The price after discount 5 percent is $ 855.0
The price after discount 10 percent is $ 810.0
The price after discount 15 percent is $ 765.0
The price after discount 20 percent is $ 720.0

# List comprehension

In [44]:
discounted_price_list = []
for x in price_list:
    discounted_price = x - (x * 5/100)
    discounted_price_list.append(discounted_price)
print(discounted_price_list)

[855.0, 807.5, 831.25, 950.0]

In [45]:
discounted_price_list = [x - (x * 5/100) for x in price_list]
print(discounted_price_list)

[855.0, 807.5, 831.25, 950.0]

In [46]:
budget = int(input("enter your budget:"))
within_budget = ['yes' if x <= budget else 'no' for x in price_list]
within_budget

enter your budget:900

['yes', 'yes', 'yes', 'no']

# Function

In [47]:
def display_phone_features(brand, price, ram, storage):
    print(brand)
    print(price)
    print(ram)
    print(storage)
    
display_phone_features("Apple", 900, 4, 64)

Apple
900
4
64

In [48]:
def disc_price(price, discount):
    discounted_price = price - discount
    return discounted_price
    
print(disc_price(900, 10))

890

In [49]:
disc_price_lambda = lambda discount : 900 - (900 * discount / 100)
disc_price_lambda(10)

810.0

# *args

In [50]:
def total_amount(*args):
    total = 0
    for arg in args:
        total += arg
    return total

total_amount(799, 494, 389, 444, 999, 930)

4055

# **kwargs (keyword argument)

In [51]:
def total_discounted_amount(*prices, discount = 0.05): # positional argument should be always first then keyword arguments
    total = 0
    for price in prices:
        total += price
        
    total_discounted_price = total - discount * total
    return total_discounted_price
    
total_discounted_amount(100, 200, 300, 400, 500, 600)

1995.0

In [52]:
def customer_net_spend(*prices, discount=0.0, **kwargs):
    total = 0
    for price in prices:
        total += price
    total_discounted_price = total - discount * total
    net_spend = total_discounted_price - kwargs["cashback"]
    return net_spend
    
additionals = {"cashback": 10}
print(customer_net_spend(100, 200, 300, 400, 500, 600, 700, 800, discount = 0.5, **additionals))

1790.0

In [53]:
def order_summary(*prices, **additionals):
    total = 0
    for price in prices:
        total += price
    net_spend = total - additionals["discount"] * total  - additionals["cashback"]
    if total >= 10000:
        reward_points = 300
    elif total >= 5000:
        reward_points = 200
    elif total >= 2000:
        reward_points = 100
    else:
        reward_points = 0
        
    return total, net_spend, reward_points

additionals = {"discount": 0.05, "cashback": 5}
order_summary(100, 200, 300, 400, 500, 600, **additionals)

(2100, 1990.0, 100)

# OOPS

In [4]:
class My_data_type:
    def __init__(self, val1, val2):
        self.val1 = val1
        self.val2 = val2
        
    def multiply_vals(self):
        return self.val1 * self.val2

me = My_data_type(2, 3)
print(me.val1)
print(me.multiply_vals())

2
6

# Numpy

In [2]:
import numpy as np

In [3]:
# numpy arrays contain only single data type values
arr = ["audi", "bmw", "ford", "tesla", "maruti"]

In [4]:
num_arr = np.array(arr)
num_arr

array(['audi', 'bmw', 'ford', 'tesla', 'maruti'], dtype='<U6')

In [5]:
type(num_arr)

numpy.ndarray

In [6]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [7]:
type(matrix)

numpy.ndarray

In [8]:
arr2 = np.arange(start=0, stop = 10)

# or

arr2 = np.arange(0, 10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]

In [9]:
arr3 = np.arange(start=0, stop=20, step=5)

# or

arr3 = np.arange(0, 20, 5)
arr3

array([ 0,  5, 10, 15])

In [10]:
matrix2 = np.linspace(0,5) # default 50 count # stops where we ask to stop. in this case it is 5
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [11]:
matrix3 = np.linspace(10, 20, 10) # last 10 is number of elements
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [12]:
matrix4 = np.zeros([3,5])
matrix4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
matrix5 = np.ones([3,5])
matrix5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
matrix6 = np.eye(5)
matrix6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr4 = np.arange(0,10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr4_reshaped = arr4.reshape((2,5))
arr4_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
np.sin(4)

-0.7568024953079283

In [18]:
np.cos(4)

-0.6536436208636119

In [19]:
np.tan(4)

1.1578212823495775

In [20]:
np.exp(2)

7.38905609893065

In [21]:
np.sin(arr4)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [22]:
np.cos(arr4)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [23]:
np.tan(arr4)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [24]:
np.exp(arr4)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [25]:
np.log(2)

0.6931471805599453

In [26]:
arr5 = np.array([2,4,6])
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [27]:
np.log10(5)

0.6989700043360189

In [28]:
np.log2(5)

2.321928094887362

In [29]:
l1 = [1,2,3]
l2 = [4,5,6]
# list addition
print(l1+l2)

[1, 2, 3, 4, 5, 6]

In [30]:
arr7 = np.arange(1,6)
arr8 = np.arange(3,8)
print(arr7)
print(arr8)

[1 2 3 4 5]
[3 4 5 6 7]

In [31]:
print(arr7+arr8)
print(arr7-arr8)
print(arr7*arr8)
print(arr7/arr8)
print(1/arr8)
print(arr7**arr8) # power

[ 4  6  8 10 12]
[-2 -2 -2 -2 -2]
[ 3  8 15 24 35]
[0.33333333 0.5        0.6        0.66666667 0.71428571]
[0.33333333 0.25       0.2        0.16666667 0.14285714]
[    1    16   243  4096 78125]

In [32]:
matrix7 = np.arange(1,10).reshape(3,3)
print(matrix7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [33]:
matrix8 = np.eye(3)
print(matrix8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [34]:
print(matrix7+matrix8)
print(matrix7-matrix8)
print(matrix7*matrix8)
print(matrix7/matrix8)
print(matrix7**matrix8)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
[[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
[[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]
[[1. 1. 1.]
 [1. 5. 1.]
 [1. 1. 9.]]

/var/folders/rb/vxz6k1t5467dsdk0dw0msyhm0000gn/T/ipykernel_2615/530848376.py:4: RuntimeWarning: divide by zero encountered in divide
  print(matrix7/matrix8)

In [35]:
# linear algebra matrix multiplication or dot product
matrix9 = np.arange(1,10).reshape(3,3)
print(matrix9)
matrix10 = np.arange(11,20).reshape(3,3)
print(matrix10)
print(matrix9 @ matrix10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]

In [36]:
print(matrix9)
# transpose
print(matrix9.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]

In [37]:
print(np.min(matrix9))
print(np.max(matrix9))

1
9

In [38]:
rand_mat = np.random.rand(5,5)
rand_mat

array([[0.2703982 , 0.59770802, 0.09578918, 0.38108796, 0.35629814],
       [0.425693  , 0.64058553, 0.3740592 , 0.58193261, 0.81503193],
       [0.21483214, 0.22832016, 0.49353819, 0.38509117, 0.13857841],
       [0.01971428, 0.56614846, 0.48390532, 0.43114127, 0.00801088],
       [0.46437669, 0.24026858, 0.38271354, 0.29185708, 0.32572479]])

In [39]:
rand_mat2 = np.random.randn(5) #n for normal
rand_mat2

array([-0.13879153, -0.0465275 ,  0.27954644,  0.65759186,  0.37341972])

In [41]:
# std diviation
print(np.std(rand_mat2))
#mean
print(np.mean(rand_mat2))

0.28920957683206866
0.22504779846926196

In [42]:
rand_mat3 = np.random.randint(1, 5, 10)
print(rand_mat3)

[1 4 2 1 2 3 2 4 4 4]

In [76]:
rand_mat4 = np.random.randint(1, 10, [5,5])
print(rand_mat4)

[[8 5 3 2 2]
 [3 5 1 3 2]
 [6 8 7 1 9]
 [3 4 6 5 3]
 [8 9 4 6 4]]

In [45]:
rand_mat5 = np.random.randn(10)
print(rand_mat5)

[-0.44306749  2.5311557   0.7848394  -0.31528662  1.46036419  0.76315017
  0.14956647 -0.40079883 -0.93785851 -1.31675699]

In [46]:
print(rand_mat5[4])

1.4603641879778664

In [47]:
print(rand_mat5[4:9]) # 9 is excluded

[ 1.46036419  0.76315017  0.14956647 -0.40079883 -0.93785851]

In [50]:
print(rand_mat5[np.arange(3, 10, 3)])

[-0.31528662  0.14956647 -1.31675699]

In [51]:
rand_mat5[rand_mat5>0]

array([2.5311557 , 0.7848394 , 1.46036419, 0.76315017, 0.14956647])

In [52]:
rand_mat5[rand_mat5<0]

array([-0.44306749, -0.31528662, -0.40079883, -0.93785851, -1.31675699])

In [53]:
rand_mat6 = np.random.randn(5,5)
rand_mat6

array([[ 0.58022476, -0.37011814, -0.31597427, -0.9128299 , -0.66105203],
       [ 0.58003481,  0.75343406,  1.48291944,  0.46292588, -1.65566423],
       [ 1.39288281, -1.30704625, -0.2431677 ,  0.31527128, -1.77273062],
       [-2.01222757,  0.07102021, -0.06045438, -0.28193381,  0.834555  ],
       [ 0.04275651, -0.61101355, -0.90877939,  1.1566982 ,  0.87376204]])

In [54]:
rand_mat6[4]

array([ 0.04275651, -0.61101355, -0.90877939,  1.1566982 ,  0.87376204])

In [59]:
print(rand_mat6[4,4])
#or
print(rand_mat6[4][4])

0.8737620366290723
0.8737620366290723

In [63]:
rand_mat6[0:2,1:3] # rows o to 2(excluded) and collumns 1 to 3(excluded)

array([[-0.37011814, -0.31597427],
       [ 0.75343406,  1.48291944]])

In [64]:
rand_mat6[rand_mat6>0] # converts into 1 dimensional array from matrix

array([0.58022476, 0.58003481, 0.75343406, 1.48291944, 0.46292588,
       1.39288281, 0.31527128, 0.07102021, 0.834555  , 0.04275651,
       1.1566982 , 0.87376204])

In [65]:
rand_mat5[3:5] = 5 # assigns 5 to 3rd and 4th element
rand_mat5

array([-0.44306749,  2.5311557 ,  0.7848394 ,  5.        ,  5.        ,
        0.76315017,  0.14956647, -0.40079883, -0.93785851, -1.31675699])

In [66]:
rand_mat5[0:2] = [2,3]
rand_mat5

array([ 2.        ,  3.        ,  0.7848394 ,  5.        ,  5.        ,
        0.76315017,  0.14956647, -0.40079883, -0.93785851, -1.31675699])

In [67]:
rand_mat5[rand_mat5>0] = 56
rand_mat5

array([56.        , 56.        , 56.        , 56.        , 56.        ,
       56.        , 56.        , -0.40079883, -0.93785851, -1.31675699])

In [77]:
print(rand_mat4)
rand_mat4[1:3, 3:5] = 0
print("after")
print(rand_mat4)

[[8 5 3 2 2]
 [3 5 1 3 2]
 [6 8 7 1 9]
 [3 4 6 5 3]
 [8 9 4 6 4]]
after
[[8 5 3 2 2]
 [3 5 1 0 0]
 [6 8 7 0 0]
 [3 4 6 5 3]
 [8 9 4 6 4]]

In [78]:
sub_mat = rand_mat4[0:2, 0:3]
print(sub_mat)

[[8 5 3]
 [3 5 1]]

In [79]:
sub_mat[:] = 3
print(sub_mat)

[[3 3 3]
 [3 3 3]]

In [80]:
rand_mat4

array([[3, 3, 3, 2, 2],
       [3, 3, 3, 0, 0],
       [6, 8, 7, 0, 0],
       [3, 4, 6, 5, 3],
       [8, 9, 4, 6, 4]])

In [83]:
rand_mat8 = np.random.randn(5,5)
print(rand_mat8)
sub_mat2 = rand_mat8[0:2,0:3].copy() # this will not edit the main matrix
sub_mat2[:] = 3
print(sub_mat2)
print(rand_mat8)

[[ 0.56873437 -0.54560477  1.84520602  0.09514285  0.7960171 ]
 [ 0.29453122 -0.15810382  0.85929686  0.20503799  0.75438749]
 [ 0.89138253  2.04283777  0.78122612 -0.21117328 -0.53044357]
 [ 0.67163536  0.60300521  0.53511908 -0.9937859   0.64163127]
 [ 0.78917116 -0.37597196 -0.1499593   0.39389304  1.18648603]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[ 0.56873437 -0.54560477  1.84520602  0.09514285  0.7960171 ]
 [ 0.29453122 -0.15810382  0.85929686  0.20503799  0.75438749]
 [ 0.89138253  2.04283777  0.78122612 -0.21117328 -0.53044357]
 [ 0.67163536  0.60300521  0.53511908 -0.9937859   0.64163127]
 [ 0.78917116 -0.37597196 -0.1499593   0.39389304  1.18648603]]

In [84]:
randint_mat1 = np.random.randint(1,10,10).reshape(2,5)
print(randint_mat1)
print("")
randint_mat2 = np.random.randint(10,20,10).reshape(2,5)
print(randint_mat2)

[[1 3 1 2 5]
 [9 5 2 4 2]]

[[15 12 10 18 13]
 [12 13 11 19 13]]

In [85]:
np.save("/Users/jesminechaudhuri/Documents/Practice_apps/Python_Practice_Codes/first_file", randint_mat1)

In [86]:
np.savez("/Users/jesminechaudhuri/Documents/Practice_apps/Python_Practice_Codes/multiple_files", randint_mat1=randint_mat1, randint_mat2=randint_mat2)

In [87]:
loaded_arr = np.load("/Users/jesminechaudhuri/Documents/Practice_apps/Python_Practice_Codes/first_file.npy")
loaded_multi = np.load("/Users/jesminechaudhuri/Documents/Practice_apps/Python_Practice_Codes/multiple_files.npz")

print(loaded_arr)
print(loaded_multi)

[[1 3 1 2 5]
 [9 5 2 4 2]]
<numpy.lib.npyio.NpzFile object at 0x107e1ddd0>

In [88]:
print(loaded_multi["randint_mat1"])

[[1 3 1 2 5]
 [9 5 2 4 2]]

In [90]:
np.savetxt("/Users/jesminechaudhuri/Documents/Practice_apps/Python_Practice_Codes/first_file.txt",randint_mat1,delimiter=",")
rand_mat_txt = np.loadtxt("/Users/jesminechaudhuri/Documents/Practice_apps/Python_Practice_Codes/first_file.txt",delimiter=",")

print(rand_mat_txt)

[[1. 3. 1. 2. 5.]
 [9. 5. 2. 4. 2.]]

# Pandas

In [2]:
import pandas as pd

In [92]:
med_price_list = [100, 200, 300, 400, 500]
med_price_arr = np.array(med_price_list)

series_list = pd.Series(med_price_list)
series_arr = pd.Series(med_price_arr)

print(series_list)
print(series_arr)

0    100
1    200
2    300
3    400
4    500
dtype: int64
0    100
1    200
2    300
3    400
4    500
dtype: int64

In [93]:
med_price_list_labeled = pd.Series(med_price_list, index=["Omez", "Cetzin", "Azithral", "Dolo", "Paracetamal"])
print(med_price_list_labeled)

Omez           100
Cetzin         200
Azithral       300
Dolo           400
Paracetamal    500
dtype: int64

In [3]:
operators = ["AT&T", "Verizon", "T-Mobile", "US-Celluar"]
revenue = [171, 150, 120, 190]

telecom = pd.Series(revenue, index=operators)
telecom

AT&T          171
Verizon       150
T-Mobile      120
US-Celluar    190
dtype: int64

In [4]:
telecom[0]

171

In [5]:
telecom[:3]

AT&T        171
Verizon     150
T-Mobile    120
dtype: int64

In [6]:
telecom[-2:]

T-Mobile      120
US-Celluar    190
dtype: int64

In [8]:
telecom[[0,2,3]]

AT&T          171
T-Mobile      120
US-Celluar    190
dtype: int64

In [10]:
telecom[["AT&T", "US-Celluar"]]

AT&T          171
US-Celluar    190
dtype: int64

In [35]:
store_data = pd.DataFrame({"customer_id": ["cust01", "cust02", "cust03", "cust04"],
               "location": ["Chicago", "Austin", "Seatlle", "LA"],
               "gender": ["M", "M", "F", "F"],
               "type": ["electronics", "groceries", "medicine", "beauty"],
               "quantity": [1,2,3,4]})
store_data

  customer_id location gender         type  quantity
0      cust01  Chicago      M  electronics         1
1      cust02   Austin      M    groceries         2
2      cust03  Seatlle      F     medicine         3
3      cust04       LA      F       beauty         4

In [36]:
store_data[:1]

  customer_id location gender         type  quantity
0      cust01  Chicago      M  electronics         1

In [37]:
store_data["location"]

0    Chicago
1     Austin
2    Seatlle
3         LA
Name: location, dtype: object

In [38]:
store_data[::2]

  customer_id location gender         type  quantity
0      cust01  Chicago      M  electronics         1
2      cust03  Seatlle      F     medicine         3

In [39]:
store_data[::-1]

  customer_id location gender         type  quantity
3      cust04       LA      F       beauty         4
2      cust03  Seatlle      F     medicine         3
1      cust02   Austin      M    groceries         2
0      cust01  Chicago      M  electronics         1

In [40]:
store_data.loc[1]

customer_id       cust02
location          Austin
gender                 M
type           groceries
quantity               2
Name: 1, dtype: object

In [41]:
store_data.loc[[1,3],["location", "type"]]

  location       type
1   Austin  groceries
3       LA     beauty

In [42]:
store_data.iloc[[1,3],[1, 4]]

  location  quantity
1   Austin         2
3       LA         4

In [43]:
store_data[3, "type"] = "Electronics"
store_data

  customer_id location gender         type  quantity    (3, type)
0      cust01  Chicago      M  electronics         1  Electronics
1      cust02   Austin      M    groceries         2  Electronics
2      cust03  Seatlle      F     medicine         3  Electronics
3      cust04       LA      F       beauty         4  Electronics